<?php

/**
 * @file
 * mp_state_machine main module file.
 */

include_once 'mp_state_machine.info.inc';
include_once 'includes/mp_state_machine.states.inc';

/**
 * Implements hook_views_api().
 */
function mp_state_machine_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'mp_state_machine') . '/includes/views',
  );
}

/**
 * Implements hook_entity_load();
 */
function mp_state_machine_entity_load($entities, $entity_type) {
  $entity_type_state_types = mp_state_machine_entity_type_state_types();
  if (in_array($entity_type, array_keys($entity_type_state_types))) {
    if ($state_types = $entity_type_state_types[$entity_type]) {
      foreach (array_keys($state_types) as $state_type) {
        foreach ($entities as &$entity) {
          $state_machine = mp_state_machine_load($entity_type, $entity, $state_type);
          $entity->$state_type = $state_machine->get_current_state();
        }
      }
    }
  }
}

/**
 * Implements hook_entity_insert().
 */
function mp_state_machine_entity_insert($entity, $entity_type) {
  $entity_type_state_types = mp_state_machine_entity_type_state_types();
  if (in_array($entity_type, array_keys($entity_type_state_types))) {
    if ($state_types = $entity_type_state_types[$entity_type]) {
      foreach (array_keys($state_types) as $state_type) {
        $state_machine = mp_state_machine_load($entity_type, $entity, $state_type);
        $state_machine->persist();
      }
    }
  }
}

/**
 * Implements hook_entity_update().
 */
function mp_state_machine_entity_update($entity, $entity_type) {
  if ($entity_type == 'commerce_order') {

    // If order status was changed, let's update its state machine too.
    if ($entity->status != $entity->original->status) {
      mp_state_machine_order_state_update($entity);
    }
    // If order status was not changed, we still need to update its revision.
    else {
      mp_state_machine_order_state_keep($entity);
    }
  }
}

/**
 * Update order state machine if order status has been updated.
 *
 * @param object $order
 *   An order which has just been updated.
 *
 * @see mp_state_machine_entity_insert()
 * @see mp_state_machine_entity_update()
 */
function mp_state_machine_order_state_update($order) {
  $state_machine = mp_state_machine_load('commerce_order', $order, MP_STATE_MACHINE_CHECKOUT_STATE);

  // Update order state.
  $event_name = 'to_' . $order->status;
  $state_machine->fire_event($event_name);

  // Update states of all order's line items.
  if (!empty($order->commerce_line_items)) {
    $wrapper = entity_metadata_wrapper('commerce_order', $order);
    foreach ($wrapper->commerce_line_items as $line_item_wrapper) {
      $line_item_state_machine = mp_state_machine_load('commerce_line_item', $line_item_wrapper->value(), MP_STATE_MACHINE_CHECKOUT_STATE);
      // Only update line item's state if it is a new line item, or its current
      // state is the same as order's previous state. This is because the line
      // item's state might differ from the order's state, and in such situation
      // we do not want to update them automatically together with the order.
      if (empty($order->original) || $line_item_state_machine->get_current_state() == $order->original->status) {
        $state_machine->fire_event($event_name);
      }
    }
  }
}

/**
 * Persist order state machine if order status has not been updated.
 *
 * @param object $order
 *   An order which has just been updated.
 *
 * @see mp_state_machine_entity_insert()
 * @see mp_state_machine_entity_update()
 */
function mp_state_machine_order_state_keep($order) {
  // If a new order revision was created, but order status was not changed,
  // let's just persist all order states, to save a new entry for each state
  // in the database with the new order revision_id.
  $entity_type_state_types = mp_state_machine_entity_type_state_types();
  if ($entity_type_state_types['commerce_order']) {
    foreach (array_keys($entity_type_state_types['commerce_order']) as $state_type) {
      $state_machine = mp_state_machine_load('commerce_order', $order, $state_type);
      $state_machine->persist();
    }
  }
  // No need to do anything with line items, as they don't support revisions.
}

/**
 * Inform external systems about a workflow transition.
 *
 * @param \MPStateFlow $state_machine
 *   A state machine object used to fire the event.
 * @param string $event_key
 *   A name of the event that has just been fired.
 *
 * @see MPStateFlow::fire_event()
 */
function mp_state_machine_invoke_event_handlers(MPStateFlow $state_machine, $event_key) {
  // Load related objects.
  $entity_type = $state_machine->get_entity_type();
  $entity = entity_load_single($entity_type, $state_machine->get_entity_id());

  if (is_object($entity)) {
    $state_type = $state_machine->get_state_type();
    $state = $state_machine->get_current_state();

    // Invoke the Rules state_flow_event_fired event.
    if (module_exists('rules')) {
      rules_invoke_event('mp_state_machine_event_fired', $entity_type, $entity, $state_type, $state, $event_key);
    }

    module_invoke_all('mp_state_machine_event_fired', $entity_type, $entity, $state_type, $state, $event_key);
  }
}

/**
 * Implements hook_entity_view_alter().
 *
 * Displays order states on the admin order view page.
 *
 * @see mp_entities_preprocess_entity_property()
 */
function mp_state_machine_commerce_order_view_alter(&$build) {
  // Add MP State Machine states.
  $entity_type_state_types = mp_state_machine_entity_type_state_types();
  if (!empty($entity_type_state_types['commerce_order'])) {
    foreach ($entity_type_state_types['commerce_order'] as $state_type_name => $state_type_info) {
      $build['mp_state_machine_' . $state_type_name] = array(
        '#theme' => 'entity_property',
        '#label_hidden' => FALSE,
        '#label' => $state_type_info['label'],
        '#title_attributes' => array('abc' => 'cba'),
        '#entity_type' => 'commerce_order',
        '#entity_wrapped' => entity_metadata_wrapper('commerce_order', $build['#entity']),
        '#property_name' => $state_type_name,
        '#weight' => -6,
      );
    }
  }
}

/**
 * Implements hook_preprocess_HOOK() for theme_entity_property().
 *
 * @see mp_entities_commerce_order_view_alter()
 */
function mp_state_machine_preprocess_entity_property(&$variables, $hook) {
  // Add field classes to make labels bold.
  $variables['attributes_array']['class'][] = 'field';
  $variables['title_attributes_array']['class'][] = 'field-label';
}
